const navigationItems: { [key: string]: string } = {
    "Dashboard": "/dashboard",
    "Club": "/club/overview",
    "Kontakt": "/club/overview?tab-contact",
    "Mitglieder": "/club/member",
    "Mitglieder / Mitglieder einladen": "/club/member?tab=invite",
    "Mitglieder / Mitgliedsbeiträge": "/club/member?tab=fee",
    "Mitglieder / Rollen": "/club/member?tab=role",
    "Chat": "/club/chat",
    "Community": "/club/community",
    "Finanzen": "/club/finance",
    "Finanzen / Buchung": "/club/finance",
    "Finanzen / Kontobewegungen": "/club/finance?tab=transaction",
    "Finanzen / Einstellungen": "/club/finance?tab=setting",
    "Grow-Control": "/club/grow",
    "Grow-Control / Strains": "/club/grow",
    "Grow-Control / Zone": "/club/grow?tab=zone",
    "Grow-Control / Chargen": "/club/grow?tab=charge",
    "Grow-Control / Pflanzen": "/club/grow?tab=plant",
    "Grow-Control / Ernten": "/club/grow?tab=harvest",
    "Inventar": "/club/inventory",
    "Inventar / Übersicht": "/club/inventory",
    "Inventar / Cannabis": "/club/inventory?tab=cannabis",
    "Inventar / Vermehrungsmaterial": "/club/inventory?tab=material",
    "Inventar / Lagerorte": "/club/inventory?tab=storage",
    "Abgabe": "/club/delivery",
    "Abgabe / Übersicht": "/club/delivery",
    "Abgabe / Abgaben": "/club/delivery?tab=tax",
    "Abgabe / Produkte": "/club/delivery?tab=product",
    "Ereignisse": "/club/event",
    "Einstellungen": "/club/profile",
    "Einstellungen / Profil": "/club/profile",
    "Einstellungen / Allgemein": "/club/profile/general",
    "Einstellungen / Design": "/club/profile/design",
    "Einstellungen / Dokumente": "/club/profile/document",
    "Einstellungen / Clubfragen": "/club/profile/question",
    "Einstellungen / Behörden": "/club/profile/authorities",
    "Mein Profil": "/profile",
    "Mein Profil / Profil": "/profile",
    "Mein Profil / Buchungen": "/profile?tab=bookings",
    "Mein Profil / Account": "/profile?tab=account",
    "Clubsuche": "/dashboard/search",
    "CanSult Academy": "/academy",
    "Brokkolikarte": "/broccoli",
  };
  
  export default navigationItems;
  